name = "Based Client"
author = "wiryfuture"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f2785909db3ea028918b3ec718786da034233375bd6b253520baa3de74dc854"

[versions]
minecraft = "1.19.2"
quilt = "0.17.5-beta.2"
