name = "Based Client"
author = "wiryfuture"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "87e68a86bd58a5ed6b39b968ba62859d1ae997aa40aa19ce5d5fd20208fbbf2c"

[versions]
minecraft = "1.19.2"
quilt = "0.17.5-beta.2"
