name = "Based Client"
author = "wiryfuture"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f12bc5868b84e35a9b46a6e042d7d78e6bc2f9d94ba6529919bce4b1a7e12c09"

[versions]
minecraft = "1.19.3"
quilt = "0.18.1-beta.75"
