name = "Unbelievably Based 1 . 19 . 2"
author = "wiryfuture"
version = "1.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9eb0b7a80e3ffa41c7f4d10df20e6259207bebcd4bcc90cab37c08ad728044f"

[versions]
minecraft = "1.19.2"
quilt = "0.17.5-beta.2"
