name = "Based Client"
author = "wiryfuture"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7659db6921a4d28448f9311b7aee09fb0fdfb882c616701288d1018fba41c405"

[versions]
minecraft = "1.19.3"
quilt = "0.18.1-beta.75"
