name = "Based Client"
author = "wiryfuture"
version = "1.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d206d13fa0439c0fe989dc1f793e5562dd0db97a45282680ada60f4dfa337823"

[versions]
minecraft = "1.19.2"
quilt = "0.17.5-beta.2"
